### ISSUE TITLE
There is no build-local for generating local changes

### ISSUE THREAD

**Issue by othercorey** [cakephp/cakephp-api-docs#102]
I might be missing something, but there wasn't a way to build using the source from my local cakephp branch.  All of the targets will checkout a specific tag in SOURCE_DIR.

I also don't have a local environment to run make so I use Docker (similar to the use case in cakephp/docs).

I had to do 2 things to build locally:

1.  Add a build-local target to Makefile
2. Create a barebones Dockerfile.dev that does not copy, build or run

How do you normally test your local source api doc changes?

**Comment by markstory** [comment]
> How do you normally test your local source api doc changes?

I generally test changes to the API docs tools by building cakephp/master. I've never tried to build the API docs based on a branch in cakephp, as changes in CakePHP source code rarely break the API documentation build process.

**Comment by othercorey** [comment]
So you manually run the commands that the Makefile would run?  That's my question.  Even if I wanted to build against cakephp/master, the targets all checkout a tag.

**Comment by markstory** [comment]
The `make build-3.7` target uses origin/master as its 'tag'.

**Comment by othercorey** [comment]
I see, thanks.  I'll just keep my changes local then!
