### ISSUE TITLE
Links with text "link.link"

### ISSUE THREAD

**Issue by ravage84** [cakephp/cakephp-api-docs#112]
The link text is ``link.link`` instead of either the text given in the doc block or just the actual link. Probably an issue in the API docs generation?

![grafik](https://user-images.githubusercontent.com/625761/98535829-0da86080-2287-11eb-9f54-667bfef9a862.png)

https://api.cakephp.org/3.9/class-Cake.Http.Middleware.SecurityHeadersMiddleware.html#setReferrerPolicy

**Comment by ADmad** [comment]
Fixed in #110.
