### ISSUE TITLE
There should be a menu listing all plugins for which API docs are available.

### ISSUE THREAD

**Issue by ADmad** [cakephp/cakephp-api-docs#140]

**Comment by markstory** [comment]
We could put it in the black header bar near the version picker. The plugin/project selector should probably be first so that we can have the versions follow the project selector and be project specific.

**Comment by othercorey** [comment]
Wouldn't the page refresh after selecting a plugin? I don't know that we would show each version for each plugin in the header.

**Comment by ADmad** [comment]
> Wouldn't the page refresh after selecting a plugin? 

Yeah, it would link to the homepage of that particular plugin/project.

> I don't know that we would show each version for each plugin in the header.

Is that a problem? We already have versions for the core. The version list will be only for the particular project,

**Comment by othercorey** [comment]
That will work. Wasn't sure if he wanted to show all versions for each plugin where you select both. That would be much more difficult.
