### ISSUE TITLE
Trait methods that inheritDoc have no information

### ISSUE THREAD

**Issue by othercorey** [cakephp/cakephp-api-docs#144]
Many traits are used to implement an interface for a class. This means many methods have only `@inheritDoc` in the docblock.

When you look at the api docs for these traits, the methods all seem to be empty:

https://api.cakephp.org/4.2/trait-Cake.Collection.CollectionTrait.html#avg

![image](https://user-images.githubusercontent.com/24221186/109868834-bf501080-7c2d-11eb-8ef7-5b0787d4027f.png)

Maybe we can add a note to methods in traits that are inheriting the docblocks. We won't be able to guess what interface they're implementing, but better than leaving all the return types as `mixed`.

**Comment by ADmad** [comment]
Even static analyzers don't like this. All [these](https://github.com/cakephp/cakephp/blob/master/psalm-baseline.xml#L8) ignored errors in psalm's baseline file are due to these `@inheritDoc` in the trait.

We should probably just copy the docblocks from the relevant interfaces instead of using `@inheritDoc`.

**Comment by othercorey** [comment]
It definitely adds overhead to updating any method description, but I'm not sure there's a better universal solution.

I could certainly support a tag in the trait docblock that tells me what interface to mixin, but it wouldn't fix psalm.

**Comment by othercorey** [comment]
I'm going to solve this by using the new `excludes` config to avoid the traits that are purely implementation. Should avoid most the issues until we update the docs.
