### ISSUE TITLE
Add queue repo project to build

### ISSUE THREAD

**Issue by othercorey** [cakephp/cakephp-api-docs#155]
It should live at `https://api.cakephp.org/queue/0.x/` or `https://api.cakephp.org/queue/0.1.x/` if the version matters.

**Comment by othercorey** [comment]
@markstory Do we want to build `0.x` or `0.1, 0.2` ?

**Comment by markstory** [comment]
We can do 0.x for now. The plugin has a fairly small surface, so we can use annotations in the doc to note version compatibility.

**Comment by markstory** [comment]
Queue docs are live now https://api.cakephp.org/queue/0.x/
