### ISSUE TITLE
OpenHub badge is hard to read

### ISSUE THREAD

**Issue by othercorey** [cakephp/cakephp-api-docs#164]
@Arhell Can we make this easier to read?

![image](https://user-images.githubusercontent.com/24221186/110548913-e9567680-80f6-11eb-82e4-bda9763302da.png)

**Comment by othercorey** [comment]
Maybe use badge url https://img.shields.io/badge/OpenHUB-CakePHP-lightgrey

I don't know if there is a newer badge image.

**Comment by Arhell** [comment]
> Maybe use badge url https://img.shields.io/badge/OpenHUB-CakePHP-lightgrey
> 
> I don't know if there is a newer badge image.

Great, thank you
