### ISSUE TITLE
Email and Mailer classes have wrong methods

### ISSUE THREAD

**Issue by othercorey** [cakephp/cakephp-api-docs#185]
The `Mailer` class seems to include methods from `Email` that are not annotated. `Email` does not include all of the methods it defines.

There isn't an obvious reason these classes are being mixed.

**Comment by ADmad** [comment]
Atleast in 4.x Mailer should not include/have annotations for any methods of Email since the latter is deprecated.

**Comment by othercorey** [comment]
You're right. I was confused because I was accidentally on a 3.x branch when comparing locally.

**Comment by othercorey** [comment]
Mailer does have annotations in 4.x source though.
