### ISSUE TITLE
CakePHP API Docs Do Not Show Function Signatures On The Method Detail Portion

### ISSUE THREAD

**Issue by jtyost2** [cakephp/cakephp-api-docs#26]
This is an issue with multiple versions of the API Docs:

1.3 API: http://api.cakephp.org/1.3/class-FileEngine.html#__setKey
2.0 API: http://api.cakephp.org/2.0/class-PhpReader.html#_read
3.0 API: http://api.cakephp.org/3.0/class-Cake.Core.Configure.html#_configured

All of those method definitions don't show any of the parameters for the function signature at the method detail point.

Asked @bcrowe about this and was told this was a bug and to report an issue as such.

**Comment by markstory** [comment]
Would you expect to have any typehints and default args in the signatures?

Would it help if there was a signature under the title?

**Comment by jtyost2** [comment]
Yes: I would expect to have the typehints and default args in the signatures.
Yes: that's actually a decent solution.

Adding the signature under the title prevents the tile for the method details from being crazy long for functions that have more than about 3 args.

**Comment by markstory** [comment]
Closing as cakephp/cakephp-api-docs#28 is now open. I've added signatures, included inherited docs, and adjusted property layouts.
