### ISSUE TITLE
API documentation of CakePHP 2.x throws 404 not found

### ISSUE THREAD

**Issue by juhpir** [cakephp/cakephp-api-docs#274]
How to access CakePHP API Documentation? For example https://api.cakephp.org/2.10/ or any page under it like https://api.cakephp.org/2.10/class-Hash.html shows only **404 Not Found nginx**

Any mirrors available?

**Comment by othercorey** [comment]
@markstory

**Comment by markstory** [comment]
I'll get this fixed tonight, the containers for the 2.x docs should still be around.

**Comment by othercorey** [comment]
The 2.x docs are fixed.
