### ISSUE TITLE
Version Picker/Dropdown has non ordered entries

### ISSUE THREAD

**Issue by ritesh-pandey** [cakephp/cakephp-api-docs#42]
![screenshot from 2016-01-15 19 15 48](https://cloud.githubusercontent.com/assets/1433681/12354523/959182a6-bbbc-11e5-9b7b-e7616d9d6dc5.png)

Entry for version `2.7` appears before `2.8`. It breaks the order in the dropdown.
Please find screen shot attached.

**Comment by ritesh-pandey** [comment]
I guess a change has to be made in `config.neon` file.

**Comment by antograssiot** [comment]
updated in b2b7766. I restarted the build should be good soon
