### ISSUE TITLE
Layout: API should have syntax highlightning

### ISSUE THREAD

**Issue by markstory** [cakephp/cakephp-api-docs#50]
_From @ionas on July 4, 2016 14:37_

See for example: http://api.cakephp.org/3.2/source-class-Cake.Validation.Validation.html#505
Unobtrusive, lazy/footer loaded through JS library if possible.

_Copied from original issue: cakephp/docs#4149_

**Comment by markstory** [comment]
_From @andtxr on July 4, 2016 17:43_

Agreed!

**Comment by antograssiot** [comment]
closed as PR #58 has been opened
