### ISSUE TITLE
Layout: API anchor links are hidden by static/fixed menu

### ISSUE THREAD

**Issue by markstory** [cakephp/cakephp-api-docs#51]
_From @ionas on July 4, 2016 14:35_

http://api.cakephp.org/3.2/source-class-Cake.Validation.Validation.html#505 for instance is partially hidden at the top.

_Copied from original issue: cakephp/docs#4148_

**Comment by markstory** [comment]
_From @andtxr on July 4, 2016 17:57_

While using Chrome if I click in the link, I can view it as the first line of the content area, but if I force the page refresh, the anchor link stays hidden by the expanded top menu.

**Comment by markstory** [comment]
_From @ionas on July 4, 2016 18:2_

Safari is kind of okay. Firefox is not.

**Comment by markstory** [comment]
_From @andtxr on July 4, 2016 18:7_

* Opera has the same behavior described previously.
* Edge is rolling the anchor link to the bottom of the page.

**Comment by markstory** [comment]
The layout looks fine for me on Firefox (OSX) on both initial page load and forced refresh.

**Comment by andtxr** [comment]
![captura de tela 2016-07-05 as 09 38 44](https://cloud.githubusercontent.com/assets/7216884/16584972/edbc2954-4294-11e6-9ee8-6be6171f5f01.png)

Chrome (MacOS)
* Fine click
* Bad refresh

![captura de tela 2016-07-05 as 09 42 01](https://cloud.githubusercontent.com/assets/7216884/16584993/06f762a8-4295-11e6-8562-66a20ef8e1e9.png)

Firefox (MacOS)
* Fine click
* Fine refresh

![captura de tela 2016-07-05 as 09 47 33](https://cloud.githubusercontent.com/assets/7216884/16585107/8d909820-4295-11e6-9758-8c5cb66e96df.png)

Opera (MacOS)
* Fine click
* Bad refresh

![captura de tela 2016-07-05 as 09 49 15](https://cloud.githubusercontent.com/assets/7216884/16585165/cce595f2-4295-11e6-8444-5c9b0b7fe148.png)

Safari (MacOS)
* Fine click
* Fine refresh

**Comment by ionas** [comment]
Same here on Mac FF/Safari (did not test the others)

**Comment by antograssiot** [comment]
closing as #60 is open
