### ISSUE TITLE
add elastic search API to docs

### ISSUE THREAD

**Issue by Graziel** [cakephp/cakephp-api-docs#53]
also it would be great addition to add APIs of:
- elasticsearch
- bake
- acl

currently elastic search docs are not fully covered and many things can be found in only code

**Comment by othercorey** [comment]
@markstory elastic-search docs should be deployable now.

**Comment by ADmad** [comment]
https://api.cakephp.org/elastic-search/

**Comment by othercorey** [comment]
Added and now in project listing.
