### ISSUE TITLE
Menu links overflowing into body

### ISSUE THREAD

**Issue by birdy247** [cakephp/cakephp-api-docs#55]
When viewing the API (example page http://api.cakephp.org/3.2/class-Cake.Controller.Controller.html#_beforeRender). The menu links on the left (desktop view) are overflowing into the body of the document.  This makes it very hard to read

Thanks

**Comment by markstory** [comment]
On what browser? They look fine in Firefox 47 on OSX

![screen shot 2016-07-15 at 10 27 13](https://cloud.githubusercontent.com/assets/24086/16877562/c25778ce-4a76-11e6-9f36-baa84bd3fa9c.png)

**Comment by ADmad** [comment]
I don't like the fact that long class names wrap. It would be better to show them truncated using `text-overflow: ellipsis;` css IMO.

**Comment by ADmad** [comment]
Perhaps then with some css / js trickery the full unwrapped class name could then be shown on hover.

**Comment by ADmad** [comment]
Btw I get same display as shown by @markstory

**Comment by birdy247** [comment]
Chrome 51.0.2704.106 m

![image](https://cloud.githubusercontent.com/assets/6965315/16877830/e5a9f088-4aa1-11e6-9a67-66bfb3758297.png)

**Comment by antograssiot** [comment]
> I don't like the fact that long class names wrap. It would be better to show them truncated using text-overflow: ellipsis; css IMO.

👍

**Comment by antograssiot** [comment]
closing as #59 is open now
