### ISSUE TITLE
Layout: API Line Numbers show on top and are broken

### ISSUE THREAD

**Issue by ionas** [cakephp/cakephp-api-docs#56]
Ref: http://api.cakephp.org/3.0/source-class-Cake.ORM.Table.html
<img width="1920" alt="screen shot 2016-07-15 at 13 51 01" src="https://cloud.githubusercontent.com/assets/106845/16873385/2954ca92-4a93-11e6-9eea-22a89f15d9eb.png">

**Comment by ionas** [comment]
User Agent: Firefox 47.0 OS X

**Comment by ADmad** [comment]
It happens in chrome as well, for all source code pages.

**Comment by antograssiot** [comment]
closing as PR #57 is open now
