### ISSUE TITLE
broken code formating in API Examples

### ISSUE THREAD

**Issue by antograssiot** [cakephp/cakephp-api-docs#64]
_From @Graziel on August 3, 2016 22:6_

the code formating in Examples looks wierd (no intendation & new lines):
http://api.cakephp.org/3.2/class-Cake.ORM.Query.html#_leftJoinWith
vs
http://api.cakephp.org/3.2/source-class-Cake.ORM.Query.html#459-531

```
// Get the count of articles per user
$usersQuery ->select(['total_articles' => $query->func()->count('Articles.id')]) ->leftJoinWith('Articles') ->group(['Users.id']) ->autoFields(true);
```
vs
```
// Get the count of articles per user
$usersQuery
    ->select(['total_articles' => $query->func()->count('Articles.id')])
    ->leftJoinWith('Articles')
    ->group(['Users.id'])
    ->autoFields(true);
```

_Copied from original issue: cakephp/docs#4227_

**Comment by markstory** [comment]
Looks like another issue in ApiGen :cry:

**Comment by ADmad** [comment]
We can do the same fix that we had done earlier to replace markdown code fences with `<code></code>` when the docblocks are parsed https://github.com/cakephp/cakephp-api-docs/commit/03e11f79b82588d3884a0773d059137d8cf56d9b#diff-e720f4338c11d4e6e325beaeb53a892bR214

**Comment by antograssiot** [comment]
fixed now
