### ISSUE TITLE
Classes with non-Cake prefix are missing from sidebar class-nav

### ISSUE THREAD

**Issue by ritesh-pandey** [cakephp/cakephp-api-docs#70]
Applicable for versions < `3.0`

Classes such as `Controller`, `HtmlHelper`, `Datasource` are not present in sidebar navigation. 

Possible reason - inclusion of `main: Cake` in `apigen.neon` ?

**Comment by ritesh-pandey** [comment]
I'm trying to debug. 

How are variables such as `$classes` passed to `@layout.latte` in template? 
What is the starting point of `.latte` code?

**Comment by antograssiot** [comment]
@ritesh-pandey did you made some progress in debugging this or do you want us to have a look ?

**Comment by antograssiot** [comment]
I got it fixed, will send a PR

**Comment by ritesh-pandey** [comment]
@antograssiot I also thought of removing the `main` parameter. But then I read the documentation. 

```
      --main=MAIN                            Elements with this name prefix will be first in tree.
```

IMHO it means that only the positioning of main prefixed classes will be affected. So I started to look into `@layout.latte` and understand why the non-prefixed classes are not being rendered.

But that is where I got stuck. I was unable the understand the flow of latte templates.

Please let me know if I'm headed in wrong direction.

**Comment by antograssiot** [comment]
@ritesh-pandey it did solve the issue, I've built the api localy and also I remember that I personally add this value without noticing any changes. I should have removed it before, sorry for that

**Comment by antograssiot** [comment]
@ritesh-pandey would you please confirm that it is ok now ?

**Comment by ritesh-pandey** [comment]
Yes.
