### ISSUE TITLE
Templater docs are missing

### ISSUE THREAD

**Issue by ndm2** [cakephp/cakephp-api-docs#75]
Somehow the docs involving `\Cake\View\StringTemplate` and `\CakeView\StringTemplateTrait` are missing.

* **http://api.cakephp.org/3.3/class-Cake.View.StringTemplate.html**
* **http://api.cakephp.org/3.3/class-Cake.View.StringTemplateTrait.html**
* **http://api.cakephp.org/3.3/class-Cake.View.Helper.HtmlHelper.html#_templater**

**Comment by markstory** [comment]
Fixed now.
