### ISSUE TITLE
HTML.Helper Doc is truncated for 3.0

### ISSUE THREAD

**Issue by acomerlatto** [cakephp/cakephp-api-docs#76]
The docs involving `Cake\View\Helper\HtmlHelper` is missing.

- http://api.cakephp.org/3.0/class-Cake.View.Helper.HtmlHelper.html

**Comment by markstory** [comment]
Looks like some missing HTML escaping. I'll get that fixed.

**Comment by markstory** [comment]
The API docs are truncated as there is unescaped HTML content in the 3.0 and 3.1 branches. The 3.2 and 3.3 docs don't have this issue as we corrected the doc block comments in 3.2. I'll look into possibly releasing a new point release of 3.0 and 3.1 to fix the API docs issues.

**Comment by markstory** [comment]
Docs for 3.0 and 3.1 are fixed.
