### ISSUE TITLE
Broken .zip exports on api.cakephp.org

### ISSUE THREAD

**Issue by Thibaut** [cakephp/cakephp-api-docs#78]
The ZIP exports on api.cakephp.org are broken. E.g.:
https://api.cakephp.org/3.3/CakePHP-API-documentation.zip (no docs inside; only `resources/`)

**Comment by markstory** [comment]
We might have to remove the button then. The tool we use to build the API is not well maintained anymore.

**Comment by antograssiot** [comment]
closing, a PR is open to remove the button, ApiGen even removed this feature now :(
