### ISSUE TITLE
Can not see the document of version 1.1?

### ISSUE THREAD

**Issue by tenkoma** [cakephp/cakephp-api-docs#83]
The following parts of the [nginx.conf](https://github.com/cakephp/cakephp-api-docs/blob/master/nginx.conf)  do not seem to work.

```
    location ~ ^/1\.1(.*)$ {
        return 301 http://api11.cakephp.org/;
    }

    location ~ ^/class/.*$ {
        return 301 http://api.cakephp.org/2.6$request_uri;
    }
```

* http://api11.cakephp.org/ -> After redirecting to https://api11.cakephp.org/ , you will see "Service Unavailable".
* https://api.cakephp.org/class/package-Cake.Cache.Engine.html -> After redirecting to https://api.cakephp.org/2.6/class/package-Cake.Cache.Engine.html, you will see "Not Found"

**Comment by markstory** [comment]
The 1.1 redirect is totally broken. We aren't able to build the API docs for the 1.1 releases as the 1.1.x tags were lost when we moved from SVN to git way back.

**Comment by josegonzalez** [comment]
I *do* have a local cache of all the old websites locally. However, you have the codebase locally, and we just extract the api docs from there so it shouldn't be absolutely necessary.

**Comment by markstory** [comment]
I'm kind of OK not having the 1.1 docs online anymore. 1.1 is almost 10 years old now.

**Comment by markstory** [comment]
Closing as we won't have 1.1 docs anytime soon.
