### ISSUE TITLE
404 for Constants summary links 

### ISSUE THREAD

**Issue by saeideng** [cakephp/cakephp-api-docs#95]
https://api.cakephp.org/3.5/class-Cake.ORM.Association.html#MANY_TO_MANY
click to one of link bellow the `Constants summary`
for example 
https://api.cakephp.org/3.5/source-constant-MANY_TO_MANY.html#76-81

**Comment by markstory** [comment]
This could be a problem with apigen. Unfortunately that project doesn't have the best release cycle.
